Check for key name

diff --git a/.local/bin/generate-ssh-key b/.local/bin/generate-ssh-key
--- a/.local/bin/generate-ssh-key
+++ b/.local/bin/generate-ssh-key
@@ -1,11 +1,18 @@
 #!/bin/bash
 
+# Check if a parameter is given
+if [ -z "$1" ]; then
+    echo "Error: No key name provided."
+    echo "Usage: $0 <key_name>"
+    echo "Key names to use for git: git_me, git_im, git_uni"
+    exit 1
+fi
+
 key_name=$1
 
 # Directory to hold SSH keys for the sfaiz user
 # SSH_DIR="$HOME/.ssh"
 SSH_DIR=$(pwd)
-
 
 # SSH key files
 PRIVATE_KEY="$SSH_DIR/$key_name"
@@ -28,4 +35,3 @@ fi
 # Output the public key
 echo "Copy the following SSH public key and add it to your GitHub account:"
 cat "$PUBLIC_KEY"
-
